name: Deploy Docs to Cloudflare Workers

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: macos-26
    
    environment:
      name: production
      url: https://docb.app/documentation
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build DocC
        run: |
          swift package \
          --allow-writing-to-directory ./docs \
          generate-documentation \
          --target DocBCore \
          --target DocCKit \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path / \
          --experimental-skip-synthesized-symbols \
          --enable-experimental-combined-documentation \
          --output-path ./docs

      - name: Deploy to Cloudflare Workers
        id: cloudflare_deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: deploy worker.js
